spring:
  datasource:
    drive-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/malote
    password: 123
  jpa:
    hibernate:
      generate-ddl: false
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    messages:
      basename: messages
logging:
  level:
    org.springframework: INFO