package com.es.maloteapi.exception;

public enum ProblemKey {
    USUARIO_EXISTENTE,
    USUARIO_INEXISTENTE,
    CREDENCIAIS_INVALIDAS,
    ERRO_AO_BUSCAR_USUARIO,
    USUARIO_JA_POSSUI_CATEGORIAS_PADRAO,

    CATEGORIA_INEXISTENTE,

    CATEGORIA_PADRAO_INEXISTENTE,

    CONTA_INEXISTENTE,

    DESPESA_INEXISTENTE,

    SALDO_INSUFICIENTE
}
